
---
title: Jekyll URL Shortener
permalink: /✂️🔗/
redirect_to: https://hlaueriksson.github.io/jekyll-url-shortener/
---

title: hlaueriksson.me
description: URL Shortener for projects made by Henrik Lau Eriksson ✂️🔗
logo: /assets/img/logo.png
show_downloads: true
google_analytics: UA-39767110-9
theme: jekyll-theme-minimal

permalink: /:slug/

plugins:
  - jekyll-redirect-from

#repository: hlaueriksson/hlaueriksson.me
